Refine run script

diff --git a/benchmarks/native-image-run b/benchmarks/native-image-run
--- a/benchmarks/native-image-run
+++ b/benchmarks/native-image-run
@@ -3,14 +3,22 @@
 set -e
 
 if [[ -z "${GRAALVM_HOME}" ]]; then
-  echo "GRAALVM_HOME is not set"
-  exit 1
+    echo "GRAALVM_HOME is not set"
+    exit 1
 fi
 
 if test "$#" -ne 2; then
-  echo "Expect 2 argument, found = $#"
-  echo "Usage: ./native-image-run <launchers-dir> <benchmark>"
-  exit 1
+    echo "Expect 2 argument, found = $#"
+    echo "Usage: ./native-image-run <launchers-dir> <benchmark>"
+    echo ""
+    echo "The script helps to run the benchmarks with GraalVM Native Image."
+    echo "It will first run the Java agent to collect reflection and resource"
+    echo "information, and then supply the information as intput to Native"
+    echo "Image compiler."
+    echo ""
+    echo "Prerequisite:"
+    echo "- The GRAALVM_HOME environment variable should be set."
+    exit 1
 fi
 
 AGENT="$GRAALVM_HOME/bin/java"
@@ -23,51 +31,60 @@ JAR="$LAUNCHERS_DIR/$BENCHMARK.jar"
 CONFIG_DIR=$BENCHMARK-config
 
 fix_data_dir(){
-  parent_dir="$(dirname "$LAUNCHERS_DIR")"
-  echo "Data-Location=$parent_dir" > ~/.dacapo-config.properties
+    parent_dir="$(dirname "$LAUNCHERS_DIR")"
+    echo "Data-Location=$parent_dir" > ~/.dacapo-config.properties
 }
 
 run_agent(){
-  $AGENT -agentlib:native-image-agent=config-output-dir=$CONFIG_DIR -jar "$JAR" $BENCHMARK
+    # Run agent to collect reflection and resource information
+    echo "Collecting reflection and resource usage information..."
+    $AGENT -agentlib:native-image-agent=config-output-dir=$CONFIG_DIR -jar "$JAR" $BENCHMARK
 }
 
 run_native_image(){
-  $NATIVE_IMAGE -H:ConfigurationFileDirectories=./$CONFIG_DIR -jar "$JAR" "$@"
+    echo "Running Native Image compilation..."
+    $NATIVE_IMAGE -H:ConfigurationFileDirectories=./$CONFIG_DIR -jar "$JAR" "$@"
 }
 
 fix_data_dir
 
+# check existence of launcher JAR
+if [ ! -f "$JAR" ]; then
+    echo "The launcher for $BANCHMARK cannot be found: $JAR"
+    exit 1
+fi
+
 case "$BENCHMARK" in
     "avrora" | "batik" | "biojava" | "graphchi" | "h2" | "sunflow")
-      run_agent
-      run_native_image
-      ./$BENCHMARK $BENCHMARK;;
+        run_agent
+        run_native_image
+        ./$BENCHMARK $BENCHMARK;;
 
     "fop")
-      config_file=$CONFIG_DIR/empty
-      touch $config_file
-      run_agent
-      run_native_image                                                             \
-          --initialize-at-run-time=org.apache.fop.render.rtf.rtflib.rtfdoc.RtfList \
-          -Djava.util.logging.config.file=$config_file                             \
+        config_file=$CONFIG_DIR/empty
+        touch $config_file
+        run_agent
+        run_native_image                                                             \
+            --initialize-at-run-time=org.apache.fop.render.rtf.rtflib.rtfdoc.RtfList \
+            -Djava.util.logging.config.file=$config_file                             \
 
-      ./$BENCHMARK -Djava.home=$GRAALVM_HOME $BENCHMARK;;
+        ./$BENCHMARK -Djava.home=$GRAALVM_HOME $BENCHMARK;;
 
     "lusearch" | "luindex")
-      run_agent
-      run_native_image
-      ./$BENCHMARK -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false --no-validation $BENCHMARK;;
+        run_agent
+        run_native_image
+        ./$BENCHMARK -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false --no-validation $BENCHMARK;;
 
     "pmd")
-      run_agent
-      run_native_image
-      ./$BENCHMARK --no-validation $BENCHMARK;;
+        run_agent
+        run_native_image
+        ./$BENCHMARK --no-validation $BENCHMARK;;
 
     "xalan")
-      run_agent
-      run_native_image "--initialize-at-build-time=org.apache.crimson.parser.Parser2,org.apache.crimson.parser.Parser2\$Catalog,org.apache.crimson.parser.Parser2\$NullHandler,org.apache.xml.utils.res.CharArrayWrapper"
+        run_agent
+        run_native_image "--initialize-at-build-time=org.apache.crimson.parser.Parser2,org.apache.crimson.parser.Parser2\$Catalog,org.apache.crimson.parser.Parser2\$NullHandler,org.apache.xml.utils.res.CharArrayWrapper"
 
-      ./$BENCHMARK $BENCHMARK;;
+        ./$BENCHMARK $BENCHMARK;;
 
 
     *)
